# Generated by Django 3.1.2 on 2020-10-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarAvailability',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_id', models.IntegerField()),
                ('rented', models.DateField()),
                ('ava', models.DateField()),
            ],
        ),
    ]
