# Generated by Django 3.1.2 on 2020-10-30 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('zip', models.IntegerField()),
                ('street_address', models.CharField(max_length=15)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Tiers',
            fields=[
                ('tier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tier_type', models.CharField(max_length=15)),
                ('tier_discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_make', models.CharField(max_length=15)),
                ('vehicle_model', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(max_length=15)),
                ('vehicle_year', models.CharField(max_length=15)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrental.location')),
                ('tier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrental.payment_tiers')),
            ],
        ),
        migrations.DeleteModel(
            name='CarAvailability',
        ),
    ]
